name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    outputs:
      env: ${{ steps.Update-Minor-Version.outputs.env }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Update-Minor-Version
      id: step1
      run: |
        cd myapp
        current_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        new_version=$(echo $current_version | awk -F '.' '{printf "%d.%d.%d", $1, $2+1, 0}')
        mvn versions:set -DnewVersion=${new_version}
        #echo "NEW_VERSION=${new_version}" >> $GITHUB_ENV
        #echo "NEW_VERSION set to: $new_version"
        #echo $new_version > version.txt
        #cp version.txt $GITHUB_WORKSPACE
        echo $new_version > $GITHUB_WORKSPACE/version.txt


    - name: Build-with-Maven
      run: |
        mvn -B package --file ./myapp/pom.xml
        pwd
        ls -l 
        ls -l ./myapp
        ls -l $GITHUB_WORKSPACE
        echo "Output from Step 1: $(cat $GITHUB_WORKSPACE/version.txt)"
        #echo "Output from Step 1: ${{ env.NEW_VERSION }}"
        #echo "::set-output name=env::${{ env.NEW_VERSION }}"

  build2:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        path: ./myapp
        
    - name: build-with-Docker
      run: |
        echo "Output from Step 1: $(cat $GITHUB_WORKSPACE/version.txt)"
        #echo "Output from Step 1: $(cat myapp/version.txt)"
        #echo "Output from Step 1: ${{ needs.build.outputs.env }}"
        #echo "Output from Step 1: ${{ needs.build.outputs.env.NEW_VERSION }}"
        # docker build -t myapp --build-arg PROJECT_VERSION=${{ env.NEW_VERSION }} .
